In [23]:
import numpy as np
def LinearRegression(x,y):
  x_m = np.mean(x)
  y_m = np.mean(y)
  numerator = 0
  denominator = 0
  n = len(x)
  for i in range(n):
    numerator = numerator + (x[i]-x_m) * (y[i]-y_m)
    denominator = denominator + (x[i]-x_m) ** 2
  m = numerator / denominator
  c = y_m - (m * x_m)
  return m,c

x=[1,2,3,4,5]
y=[3,4,2,4,5]

m,c = LinearRegression(x,y)
print(f"y={m}x + {c}")

y=0.4x + 2.4


In [24]:
def Predict(x):
  y_p = []
  for i in range(len(x)):
    y_p.append(m * x[i] + c)
  return y_p
y_p = Predict(x)
print(f"y = {y_p}")

y = [2.8, 3.2, 3.6, 4.0, 4.4]


In [25]:
y_m = np.mean(y)
r2 = 1 - ((sum(y_p - y_m) ** 2) / (sum(y - y_m) ** 2))
print(f"r2 = {r2}")

r2 = 1.0


In [26]:
y,y_p

([3, 4, 2, 4, 5], [2.8, 3.2, 3.6, 4.0, 4.4])

In [27]:
def r2score(y,y_p):
  ym = np.mean(y)
  print(ym)
  numerator = 0
  denominator = 0
  n = len(y)
  for i in range(n):
    numerator = numerator + (y_p - ym) ** 2
    denominator = denominator + (y - ym) ** 2
  return numerator / denominator;
r2score(y,y_p)


3.6


array([1.77777778, 1.        , 0.        , 1.        , 0.32653061])

In [29]:
print(f"Accuracy : {1 - r2score(y,y_p)}")

3.6
Accuracy : [-0.77777778  0.          1.          0.          0.67346939]


In [30]:
import pandas as pd
df = pd.read_csv("headbrain.csv")
df.head()

Gender  Age Range  Head Size(cm^3)  Brain Weight(grams)
0       1          1             4512                 1530
1       1          1             3738                 1297
2       1          1             4261                 1335
3       1          1             3777                 1282
4       1          1             4177                 1590

In [31]:
import numpy as np
def LinearRegression(x,y):
  x_m = np.mean(x)
  y_m = np.mean(y)
  numerator = 0
  denominator = 0
  n = len(x)
  for i in range(n):
    numerator = numerator + (x[i]-x_m) * (y[i]-y_m)
    denominator = denominator + (x[i]-x_m) ** 2
  m = numerator / denominator
  c = y_m - (m * x_m)
  return m,c

x=df["Head Size(cm^3)"].values
y=df["Brain Weight(grams)"].values

m,c = LinearRegression(x,y)
print(f"y={m}x + {c}")


y=0.26342933948939945x + 325.57342104944223


In [32]:
def predict(x):
  y_p = []
  for i in range(len(x)):
    y_p.append(m * x[i] + c)
  return y_p
y_p = predict(x)
print(f"y = {y_p}")

y = [1514.1666008256125, 1310.2722920608173, 1448.0458366137732, 1320.546036300904, 1425.9177720966638, 1269.9676031189392, 1322.6534710168191, 1263.118440292215, 1277.3436246246424, 1374.549050896231, 1232.5606369114446, 1377.4467736306142, 1284.4562167908562, 1434.0840816208351, 1335.034649972821, 1346.6255409103546, 1246.785821243872, 1238.6195117197008, 1140.8872267691336, 1490.9848189505453, 1347.1523995893333, 1391.4085286235525, 1327.6586284671178, 1302.8962705551141, 1576.0724956056215, 1490.721389611056, 1388.7742352286584, 1385.0862244758068, 1235.4583596458278, 1425.390913417685, 1323.1803296957978, 1325.5511937512024, 1406.424000974448, 1421.7029026648333, 1420.9126146463652, 1330.2929218620118, 1254.688701428554, 1312.9065854557114, 1203.8468389071, 1245.468674546425, 1369.2804641064429, 1248.8932559597874, 1462.271020946201, 1327.6586284671178, 1343.2009594969923, 1388.2473765496795, 1460.427015569775, 1159.3272805333913, 1284.7196461303456, 1285.509934148814, 1350.576981

In [33]:
y_m = np.mean(y)
r2 = 1 - ((sum(y_p - y_m) ** 2) / (sum(y - y_m) ** 2))
print(f"r2 = {r2}")

r2 = 0.8019517008853924


In [34]:
y,y_p

(array([1530, 1297, 1335, 1282, 1590, 1300, 1400, 1255, 1355, 1375, 1340,
        1380, 1355, 1522, 1208, 1405, 1358, 1292, 1340, 1400, 1357, 1287,
        1275, 1270, 1635, 1505, 1490, 1485, 1310, 1420, 1318, 1432, 1364,
        1405, 1432, 1207, 1375, 1350, 1236, 1250, 1350, 1320, 1525, 1570,
        1340, 1422, 1506, 1215, 1311, 1300, 1224, 1350, 1335, 1390, 1400,
        1225, 1310, 1560, 1330, 1222, 1415, 1175, 1330, 1485, 1470, 1135,
        1310, 1154, 1510, 1415, 1468, 1390, 1380, 1432, 1240, 1195, 1225,
        1188, 1252, 1315, 1245, 1430, 1279, 1245, 1309, 1412, 1120, 1220,
        1280, 1440, 1370, 1192, 1230, 1346, 1290, 1165, 1240, 1132, 1242,
        1270, 1218, 1430, 1588, 1320, 1290, 1260, 1425, 1226, 1360, 1620,
        1310, 1250, 1295, 1290, 1290, 1275, 1250, 1270, 1362, 1300, 1173,
        1256, 1440, 1180, 1306, 1350, 1125, 1165, 1312, 1300, 1270, 1335,
        1450, 1310, 1027, 1235, 1260, 1165, 1080, 1127, 1270, 1252, 1200,
        1290, 1334, 1380, 1140, 1243, 

In [35]:
def r2score(y,y_p):
  ym = np.mean(y)
  print(ym)
  numerator = 0
  denominator = 0
  n = len(y)
  for i in range(n):
    numerator = numerator + (y_p - ym) ** 2
    denominator = denominator + (y - ym) ** 2
  return numerator / denominator;
r2score(y,y_p)

1282.873417721519


array([8.75964972e-01, 3.76176130e+00, 1.00405281e+01, 1.86040551e+03,
       2.16923513e-01, 5.67844513e-01, 1.15350579e-01, 5.02310931e-01,
       5.87796583e-03, 9.90234188e-01, 7.75675651e-01, 9.48115805e-01,
       4.81571598e-04, 3.99861073e-01, 4.85333612e-01, 2.72501501e-01,
       2.30743062e-01, 2.35118537e+01, 6.17754237e+00, 3.15704524e+00,
       7.51951838e-01, 6.91766443e+02, 3.23550934e+01, 2.41915774e+00,
       6.93310180e-01, 8.75569276e-01, 2.61412859e-01, 2.55719451e-01,
       3.05521948e+00, 1.08017236e+00, 1.31670129e+00, 8.19017970e-02,
       2.31933371e+00, 1.29223952e+00, 8.56830108e-01, 3.90602233e-01,
       9.35960273e-02, 2.00176555e-01, 2.84245188e+00, 1.29468357e+00,
       1.65694941e+00, 8.37685389e-01, 5.48969643e-01, 2.43288982e-02,
       1.11520517e+00, 5.73649157e-01, 6.33222485e-01, 3.31328585e+00,
       4.30860749e-03, 2.36984288e-02, 1.32246613e+00, 3.89385308e-01,
       1.03308377e+01, 1.11292387e+00, 7.22803646e-01, 6.41732025e-01,
      

In [37]:
print(f"Accuracy : {1 - r2score(y,y_p)}")

1282.873417721519
Accuracy : [ 1.24035028e-01 -2.76176130e+00 -9.04052810e+00 -1.85940551e+03
  7.83076487e-01  4.32155487e-01  8.84649421e-01  4.97689069e-01
  9.94122034e-01  9.76581179e-03  2.24324349e-01  5.18841947e-02
  9.99518428e-01  6.00138927e-01  5.14666388e-01  7.27498499e-01
  7.69256938e-01 -2.25118537e+01 -5.17754237e+00 -2.15704524e+00
  2.48048162e-01 -6.90766443e+02 -3.13550934e+01 -1.41915774e+00
  3.06689820e-01  1.24430724e-01  7.38587141e-01  7.44280549e-01
 -2.05521948e+00 -8.01723622e-02 -3.16701291e-01  9.18098203e-01
 -1.31933371e+00 -2.92239517e-01  1.43169892e-01  6.09397767e-01
  9.06403973e-01  7.99823445e-01 -1.84245188e+00 -2.94683573e-01
 -6.56949409e-01  1.62314611e-01  4.51030357e-01  9.75671102e-01
 -1.15205169e-01  4.26350843e-01  3.66777515e-01 -2.31328585e+00
  9.95691393e-01  9.76301571e-01 -3.22466125e-01  6.10614692e-01
 -9.33083773e+00 -1.12923869e-01  2.77196354e-01  3.58267975e-01
 -5.18082844e+00  7.44253937e-01 -1.83109041e+00  9.77048113e