In [1]:
import numpy as np

In [15]:
# 1.	Array Creation
# 	    Create a 1D array of numbers from 10 to 50.
#   	Create a 3x3 array of random numbers between 0 and 1.
array1 = np.array(range(10,51))
print(array1,'\n')
array2 = np.random.rand(3, 3)
print(array2)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50] 

[[0.93213466 0.3563097  0.52871425]
 [0.91517346 0.27915632 0.50701428]
 [0.26227119 0.1569529  0.37791468]]


In [9]:
# 2.	Array Attributes
#    	Find the shape, size, and data type of the array you created in the previous task.
print(array1.shape)
print(array1.size)
print(array1.dtype)

(40,)
40
int32


In [10]:
# 3.	Basic Operations
#   	Add 5 to every element of a 1D array.
#       Multiply two 2D arrays element-wise.
array3 = np.array([11,21,15,31,40])
print(array3+5,"\n")

array4 = np.array([[31,14,21],[51,26,17]])
array5 = np.array([[18,19,40],[22,14,46]])
print(array4*array5)

[16 26 20 36 45] 

[[ 558  266  840]
 [1122  364  782]]


In [14]:
# 4.	Indexing and Slicing
#   	Create a 5x5 array of integers from 1 to 25. Extract:
#   	The first row.
#   	The last column.
#   	A subarray of the first three rows and first two columns.
array6 = np.array(range(1,26)).reshape(5,5)
print(array6,'\n')
print(array6[0,:],'\n')
print(array6[:,-1],'\n')
print(array6[:3,:2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]] 

[1 2 3 4 5] 

[ 5 10 15 20 25] 

[[ 1  2]
 [ 6  7]
 [11 12]]


In [17]:
# 5.	Aggregation
#   	Create a 10-element array of random integers between 1 and 100. Find:
#   	The maximum value.
#   	The minimum value.
#   	The mean and standard deviation.
array7 = np.random.randint(1,101,10)
print(array7,'\n')
print(np.max(array7),'\n')
print(np.min(array7),'\n')
print(np.mean(array7),'\n')
print(np.std(array7))

[72 88 43 31 78 73  6 20  7 96] 

96 

6 

51.4 

32.29922599691825


In [18]:
# 6.	Reshaping
#   	Convert a 1D array of numbers from 1 to 12 into a 3x4 matrix.
array8 = np.array(range(1,13)).reshape(3,4)
print(array8)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [19]:
# 7.	Broadcasting
#   	Create a 3x3 matrix of ones. Add a 1D array [1, 2, 3] to each row.
array9 = np.ones((3,3))
array10 = np.array([1,2,3])
res = array9+array10
print(res)

[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


In [ ]:
# 8.	Filtering
#   	Create a 1D array of random integers between 1 and 50. Extract all elements that are divisible by 5.
array11 = np.random.randint(1, 51, 20)
res = array11[array11 % 5 == 0]
print(res)

[25 15 15 10]


In [20]:
# 9.	Matrix Multiplication
#   	Create two 2x2 matrices and perform matrix multiplication.
array12 = np.array([[13,51],[25,37]])
array13 = np.array([[18,10],[12,41]])
print(array12*array13)

[[ 234  510]
 [ 300 1517]]


In [21]:
# 10.	Advanced Indexing
#   	Given a 4x4 array, use fancy indexing to extract the diagonal elements.
array14 = np.arange(1, 17).reshape(4, 4)
res = array14[np.arange(4), np.arange(4)]
print(res)

[ 1  6 11 16]
